dist:
  module: github.com/open-telemetry/opentelemetry-collector
  name: ebpf-demo-collector
  description: Demo OTel collector that receives network traffic
  output_path: ./otelcol-ebpf-demo
  version: 0.0.1

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.125.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/opensearchexporter v0.125.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.125.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.125.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.125.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.125.0

receivers:
  - gomod: github.com/open-telemetry/otelcol-ebpf-demo/epbf-receiver v0.0.1
    name: "ebpfreceiver"
    path: ./ebpf-receiver
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.125.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.125.0
 
connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.125.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.31.0