dist:
  module: github.com/open-telemetry/opentelemetry-collector
  name: ebpf-demo-collector
  description: Demo OTel collector that receives network traffic
  output_path: ./otelcol-ebpf-demo
  version: 0.0.1

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.117.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.117.0

receivers:
  - gomod: github.com/open-telemetry/otelcol-ebpf-demo/epbf-receiver v0.0.1
    name: "ebpfreceiver"
    path: ./ebpf-receiver

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0