receivers:
  ebpf_receiver:
    ebpf_binary_path: "ebpf-receiver/ebpf/tcp.o"
    nic_name: "cni0"

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  pg_exporter:
    dsn: "postgres://postgres:password@postgres-service.monitoring:5432/testdb"

service:
  pipelines:
    traces:
      receivers: [ebpf_receiver]
      processors: [batch]
      exporters: [debug, pg_exporter]
  telemetry:
    logs:
      level: debug