receivers:
  ebpf_receiver:
    ebpf_binary_path: "ebpf-receiver/ebpf/tcp.o"
    nic_name: "cni0"

processors:
  batch:
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.ip
    extract:
      metadata:
        - k8s.pod.name
        - k8s.deployment.name
        - k8s.node.name
        - k8s.namespace.name

exporters:
  debug:
    verbosity: detailed
  pg_exporter:
    dsn: "postgres://postgres:password@postgres-service.monitoring:5432/testdb"

service:
  pipelines:
    traces:
      receivers: [ebpf_receiver]
      processors: [batch, k8sattributes]
      exporters: [debug, pg_exporter]
  telemetry:
    logs:
      level: debug