receivers:
  ebpf_receiver:
    ebpf_binary_path: "ebpf-receiver/ebpf/tcp.o"
    nic_name: "cni0"

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [ebpf_receiver]
      processors: [batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug