apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-ebpf-demo-collector-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: otel-ebpf-demo
  template:
    metadata:
      labels:
        app: otel-ebpf-demo
    spec:
      serviceAccountName: otel-ebpf-demo-collector-daemon
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ebpf-demo-collector
        image: localhost:5000/otel-ebpf-demo:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
          name: metrics
### Exclude master node
#      tolerations:
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-ebpf-demo-collector-daemon
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-ebpf-demo-collector-daemon
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-ebpf-demo-collector-daemon
subjects:
- kind: ServiceAccount
  name: otel-ebpf-demo-collector-daemon
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: otel-ebpf-demo-collector-daemon
  apiGroup: rbac.authorization.k8s.io