FROM ubuntu:22.04

RUN apt update && apt install -y curl make clang llvm gcc git libbpf-dev
RUN ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/;s/armv7l/armv6l/') && \
    curl -LO https://go.dev/dl/go1.23.6.linux-${ARCH}.tar.gz && \
    tar -C /usr/local -xzf go1.23.6.linux-${ARCH}.tar.gz && \
    rm go1.23.6.linux-${ARCH}.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin
ENV PATH="/usr/local/go/bin:${PATH}"
RUN git config --global --add safe.directory /build