apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: otel-collector
        image: ebpf-demo-collector-image
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: GOGC
          value: "50"
        volumeMounts:
          - name: tzdata
            mountPath: /usr/share/zoneinfo
            readOnly: true
          - name: collector-config
            mountPath: /app/collector-config/
          - name: ebpf-bin
            mountPath: /app/ebpf-receiver/ebpf/
          - name: db-init
            mountPath: /app/db_init/
          - mountPath: /var/log/pods
            name: varlogpods
            readOnly: true
          - mountPath: /hostfs
            mountPropagation: HostToContainer
            name: hostfs
            readOnly: true
          - name: tracefs
            mountPath: /sys/kernel/tracing
            readOnly: true
          - name: host-proc
            mountPath: /hostproc
            readOnly: true
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 4317
          hostPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 4318
          hostPort: 4318
          name: otlp-http
          protocol: TCP
        - name: jaeger-compact
          containerPort: 6831
          protocol: UDP
        - name: jaeger-grpc
          containerPort: 14250
          protocol: TCP
        - name: jaeger-thrift
          containerPort: 14268
          protocol: TCP
        - name: metrics
          containerPort: 8888
          protocol: TCP
        - name: zipkin
          containerPort: 9411
          protocol: TCP
        - name: debug
          containerPort: 40000
          protocol: TCP
        - name: pprof
          containerPort: 6060
          protocol: TCP
      volumes:
        - name: tzdata
          hostPath:
            path: /usr/share/zoneinfo
            type: Directory
        - name: collector-config
          configMap:
            name: collector-config
        - name: ebpf-bin
          projected:
            sources:
              - configMap:
                  name: ebpf-bin-traffic
              - configMap:
                  name: ebpf-bin-pid
              - configMap:
                  name: ebpf-bin-filerw
        - name: db-init
          configMap:
            name: db-init
        - name: hostfs
          hostPath:
            path: /
            type: ""
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: ""
        - name: tracefs
          hostPath:
            path: /sys/kernel/tracing
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
### Exclude master node
#      tolerations:
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
      restartPolicy: Always
