apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-ebpf-demo-collector-daemon
spec:
  selector:
    matchLabels:
      app: otel-ebpf-demo
  template:
    metadata:
      labels:
        app: otel-ebpf-demo
    spec:
      serviceAccountName: otel-ebpf-demo-collector-daemon
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ebpf-demo-collector
        image: localhost:5000/otel-ebpf-demo:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: collector-config
            mountPath: /app/collector-config/
          - name: ebpf-bin
            mountPath: /app/ebpf-receiver/ebpf/
          - name: db-init
            mountPath: /app/db_init/
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
          name: metrics
      volumes:
        - name: collector-config
          configMap:
            name: collector-config
        - name: ebpf-bin
          configMap:
            name: ebpf-bin
        - name: db-init
          configMap:
            name: db-init
### Exclude master node
#      tolerations:
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
      restartPolicy: Always
