apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-ebpf-demo-collector-daemon
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-ebpf-demo-collector-daemon
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "nodes/stats"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-ebpf-demo-collector-daemon
subjects:
- kind: ServiceAccount
  name: otel-ebpf-demo-collector-daemon
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: otel-ebpf-demo-collector-daemon
  apiGroup: rbac.authorization.k8s.io