---
apiVersion: v1
kind: Service
metadata:
  name: otel-ebpf-demo-collector
  namespace: kube-system
spec:
  selector:
    app: otel-ebpf-demo
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: otlp-grpc
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: otlp-http
  type: ClusterIP
  